name: Terraform Deploy Lambda from ECR Image

on:
  workflow_dispatch:  
  
jobs:
  deploy:
    name: Run Terraform CD
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.2  

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform/lambda-deploy

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform/lambda-deploy

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform/lambda-deploy


